### ISSUE TITLE
Gear judge feature 

### ISSUE THREAD

**Issue by MarkusIppy** [MarkusIppy/raspexi-viewer-linux#10]
Implement Gear judge feature.
Using the Engine RPM and Speed it can determine what gear you are in.

the formula is " RPM/Speed=N " where N equals a known number relative to the gear you are in.
eg.
Gear | N=
1st | 230
2nd | 145
3rd | 94
4th | 75
5th | 50

Implement this calculation as a data source in Raspexi, so you can have a logged value of what gear you are in, as well as a visual representation on the dashboard.
N can vary a bit (+-6?) 
Needs to be user definable in CFG to cater for the various models

**Comment by JacobD10** [comment]
Coming soon ... =]

**Comment by JacobD10** [comment]
Done
