### ISSUE TITLE
Speed correction setting in CFG file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MarkusIppy/raspexi-viewer-linux#3]
```
Implement a correction value setting in the CFG file to cater for aftermarket 
wheels and diff changes . Setting in file should be set in percent , 

Eg: 

Speed correction=104 
(would show 104 percent of original read value )

```

Original issue reported on code.google.com by `Markus.I...@gmail.com` on 13 May 2014 at 10:28

**Comment by JacobD10** [comment]
This should be straight forward. I'll do this when I next have time.

**Comment by JacobD10** [comment]
Planning on using this algorithm:
e.g.
original_tyre = 195/55R15
current_tyre = 225/65R17

roll_circ_orig = (15*0.0254 + 2*(55/100)*(195/1000))*pi*0.97
roll_circ_curr = (17*0.0254 + 2*(65/100)*(225/1000))*pi*0.97
adjustment = roll_circ_curr / roll_circ_orig 

Speed_adjusted = Speed * adjustment


If you spot an error, let me know...

**Comment by JacobD10** [comment]
Will also add a simple speed_correction multiplier for easier use.
For example, more suitable to correction with GPS, stretched tyres, inflated/deflated tyres and other speed correction factors.

e.g. 3% increase in cfg file:
speed_correction = 1.03
