### ISSUE TITLE
Uniform output values for AUX 

### ISSUE THREAD

**Issue by MarkusIppy** [MarkusIppy/raspexi-viewer-linux#8]
Currently all voltage based sensor values are shown in mV
Aux inputs currently need to be multiplied by 10 to display in mV 
Hardcodeing of raw aux input to show in mV for uniformity purposes

**Comment by JacobD10** [comment]
I believe this issue stemmed from a bug which has now been fixed.
As a result the values are now displayed volts (V). This issue can be reopened if the need for mV necessary.
mV readings can also be obtained using the analog equations specified using the config file.

**Comment by MarkusIppy** [comment]
I had a look in FC edit and there it's also displayed in volts as well so I
suggest we also leave it in volts so we have uniformity with fc edit .
Haha my day keeps getting better just now all the power went off . Most
probably load shedding as this goverment forgot to build power stations 15
years ago and also didn't maintain the existing ones lol . Awesome Saturday
;)
